spring.application.name=trabalho_final_api

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/trabalho_final_api
spring.datasource.username=postgres
spring.datasource.password=1708

spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true

spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Altera o caminho para acessar o Swagger no navegador
springdoc.swagger-ui.path=/swagger-ui.html

# Altera o caminho onde o JSON do OpenAPI é gerado
springdoc.api-docs.path=/api-docs

# Configurações do Servidor SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gabriel.botelho@residente.serratec.org
spring.mail.password=teyqcikltesffmlg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jackson.deserialization.fail-on-unknown-properties=true


# Configurações do JWT
auth.jwt.secret=MeuSegredinho_DificilDeAdivinharCom_MaisDeTrintaEDoisCaracteres
auth.jwt.expiration-millis=5000

# Propriedades adicionais do JavaMail

spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Prorpiedade de tamanho de imagens
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

#Define o nível de log global do Spring para DEBUG (ou TRACE para ainda mais detalhes)
logging.level.root=DEBUG

#Mostra as queries do Hibernate/JPA com os parâmetros reais (?) preenchidos
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

#Detalhes das requisições HTTP, rotas mapeadas e respostas do Spring Web/MVC
logging.level.org.springframework.web=DEBUG

#Detalhes adicionais sobre a segurança e validação do JWT (se aplicável)
logging.level.org.springframework.security=DEBUG