spring.application.name=trabalho_final_api

server.port=${PORT}

# Configuração do Banco de Dados PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Cria/Atualiza as tabelas automaticamente (Ideal para desenvolvimento)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true

# Configurações de Log e Performance
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#Dialeto
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Altera o caminho para acessar o Swagger no navegador
springdoc.swagger-ui.path=/swagger-ui.html

# Altera o caminho onde o JSON do OpenAPI é gerado
springdoc.api-docs.path=/api-docs

# Configurações do Servidor SMTP
spring.mail.host=${EMAIL_SERVIDOR}
spring.mail.port=${EMAIL_PORT}
spring.mail.username=${EMAIL_USER}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jackson.deserialization.fail-on-unknown-properties=true


# Configurações do JWT
auth.jwt.secret=${JWT_SECRET}
auth.jwt.expiration-millis=5000

# Propriedades adicionais do JavaMail
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Prorpiedade de tamanho de imagens
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB